### ISSUE TITLE
Font file gets modified without changes

### ISSUE THREAD

**Issue by hawckins** [L2jLiga/grunt-webfonts#12]
Everything works great but, version control always shows webfont file modified, and we haven't add/delete any icons in our source directory. How do I stop modifying this file all the time except there are changes.

The issue I found is in exports.generatedFontFiles() method in util/util.js, brace expression is not working in glob.sync, so glob.sync is not returning an array of files instead it returns empty [ ] array.

will you please let me know how soon you can fix this issue? waiting for your response... If you can add me as contributor to this project, I can fix too.

**Comment by L2jLiga** [comment]
Hi there!
Feel free to fork and send PR :)

**Comment by hawckins** [comment]
I am not able to clone your repo, will you please add me as contributor? here is the error
$ Cloning into 'grunt-webfonts'...
$ ssh: connect to host github.com port 22: Network is unreachable
$ fatal: Could not read from remote repository.
$ Please make sure you have the correct access rights and the repository exists.

**Comment by hawckins** [comment]
> Hi there!
> Feel free to fork and send PR :)

I have created an PR will you please verify and merge?
