### ISSUE TITLE
Why do codepoints start at 0xF101 when the Unicode private use area is 0xE000-0xF8FF?

### ISSUE THREAD

**Issue by teamaton** [L2jLiga/grunt-webfonts#16]
First of, I have to say, that working with your plugin has been a real pleasure! I was fighting with webfont-generator and could not get it to create any files for me...

Now, in your (also really good) documentation you mention that the `startCodepoint` is by default `0xF101` because that's the beginning of the Unicode private use area.

On the [Wikipedia article](https://en.wikipedia.org/wiki/Private_Use_Areas) on the same topic I can find a different range: `0xE000` to `0xF8FF`. Why do you use `0xF101`? I feel you have a reason to do so and I would like to understand it :-)

Congratulations again and a big Thank You!
Oliver

**Comment by L2jLiga** [comment]
Hi there, sorry for long reply.
Initially this repository was forked from [`grunt-webfont`](https://github.com/sapegin/grunt-webfont) with several changes like updating dependencies to the latest available versions, compatibility with grant 1.0 and so on.

Regarding to your question - codepoint start was changed in earlier versions of [`grunt-webfont`](https://github.com/sapegin/grunt-webfont) and there are no any meaningful description of changes.

Thanks for your question!
