### ISSUE TITLE
Path variable should not be used in demo file

### ISSUE THREAD

**Issue by Th3S4mur41** [L2jLiga/grunt-webfonts#4]
When setting the parameter [fontPathVariables ](https://www.npmjs.com/package/grunt-webfonts#fontpathvariables) to true, the path to the fonts is replaced by a variable in the css/scss/less files, which is exactly what is expected in order to integrate them in other stylesheets.

However the inline style (see below) in the demo files is also generated using the variables, which makes no sense to me (I'm using less), since the variables cannot be interpreted by a browser. This is especially

```
@font-face {
	font-family:"icon";
	src:url("@{icon-font-path}circuit-svg-icons.woff2") format("woff2"),
		url("@{icon-font-path}circuit-svg-icons.woff") format("woff"),
		url("@{icon-font-path}circuit-svg-icons.ttf") format("truetype");
	font-weight:normal;
	font-style:normal;
}
```

**Comment by L2jLiga** [comment]
Thanks for the report!
I've released new version with fix
