### ISSUE TITLE
Webfont files are changed even with no changes in project

### ISSUE THREAD

**Issue by davewhitley** [L2jLiga/grunt-webfonts#43]
Hello! In my project, when I run my tasks, I get:

```
Running "webfont:icons" (webfont) task
Font social-logos wasn’t changed since last run.
```

This is expected since my project is a fresh clone of the repo (https://github.com/Automattic/social-logos). But when I check for changes, I see there are 4 files that have changes in the icon-font folder (even though I didn't change anything). A css, html, ttf, and woff2 file. The only change I can see in the html and css is a random string that is appended like so:

```
url("social-logos.ttf?c8d161ff8b1087fe5e6b0f28c56f847e") format("truetype");
```
The string being "c8d161ff8b1087fe5e6b0f28c56f847e"

Is this an issue with webfonts, why is this happening, and can it be fixed?

Thank you!

**Comment by L2jLiga** [comment]
Can't reproduce using this commit https://github.com/Automattic/social-logos/commit/083f10263159188097571b4815df670bcb2e4db2 and latest version
