### ISSUE TITLE
Icon is rendered properly on MacOS but not on Windows

### ISSUE THREAD

**Issue by Th3S4mur41** [L2jLiga/grunt-webfonts#9]
The SVG icon (eye) attached when added to the font is rendered properly on MacOS but not on Windows (see screenshot) regardless of the browser used.

[eye.zip](https://github.com/L2jLiga/grunt-webfonts/files/2826892/eye.zip)
![image](https://user-images.githubusercontent.com/5543595/52194785-934ae100-2855-11e9-949c-327205c9d804.png)

**Comment by L2jLiga** [comment]
@Th3S4mur41 sorry for late reply.

In general it seems like svgicons2svgfont bug. I guess it's related to https://github.com/nfroidure/svgicons2svgfont/issues/90

It would be helpful if you will generate svg fonts on Windows and MacOS both and check they for equality
```
options: {
  types: 'svg'
}
```

**Comment by L2jLiga** [comment]
Hi there, I think best what we can do on that is to switch engine to [FontForge](https://github.com/fontforge/fontforge) cause it generates correct font files for your usecase
![image](https://user-images.githubusercontent.com/11780854/129312161-f7787434-924c-42ef-a0a6-a08dd0075d91.png)
